MyShopLearning/MyShopLearning.WebUI/Controllers/BasketController.cs
using MyShopLearning.Core.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyShopLearning.WebUI.Controllers
{
    public class BasketController : Controller
    {
        IBasketService basketService;

        public BasketController(IBasketService BasketService)
        {
            this.basketService = BasketService;
        }
        // GET: Basket
        public ActionResult Index()
        {
            var model = basketService.GetBasketItems(this.HttpContext);
            return View(model);
        }

        public ActionResult AddToBasket(string Id)
        {
            basketService.AddToBasket(this.HttpContext, Id);

            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromBasket(string Id)
        {
            basketService.RemoveFromBasket(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        public PartialViewResult BasketSummary()
        {
            var basketSummary = basketService.GetBasketSummary(this.HttpContext);
            return PartialView(basketSummary);
        }
    }
}

MyShopLearning/MyShopLearning.WebUI/Views/Basket/BasketSummary.cshtml
@model MyShopLearning.Core.ViewModels.BasketSummaryViewModel


<ul class="nav navbar-nav navbar-right">
    <li><a href="@Url.Action("Index","Basket")">@Model.BasketCount items</a></li>
    <li><a href="@Url.Action("Index","Basket")">@String.Format("{0:c}",Model.BasketTotal)</a></li>
</ul> 

MyShopLearning/MyShopLearning.WebUI/Views/Basket/Index.cshtml
@model IEnumerable<MyShopLearning.Core.ViewModels.BasketItemViewModel>

@{
    ViewBag.Title = "Basket";
}

<h2>Baket</h2>


<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantiy)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            Line Total
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <img style="height:50px;" src="~/Content/ProductImages/@item.Image" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantiy)
        </td>
        <td>
            @String.Format("{0:c}", item.Price)
        </td>
        <td>
            @String.Format("{0:c}", item.Price * item.Quantiy)
        </td>
        <td> 
            <a href="@Url.Action("RemoveFromBasket","Basket",new { Id=item.Id})" class="btn btn-danger">Delete</a>
        </td>
    </tr>
}

    <tr>
        <td colspan="5" style="text-align:right"><strong>Basket Total</strong></td>
        <td>@String.Format("{0:c}", (from p in Model select p.Price *p.Quantiy ).Sum())</td>
    </tr>
</table>